config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
          sessions: 'users/sessions'
        }

  resources :products do
    resources :reviews
  end

  resources :users do
    resources :accounts
  end

  resources :products
  resources :order_items
  resource :cart, only: [:show]

  root to: "home#index"
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  has_many :order_items
  validates :name, :presence => true
  validates :price, :presence => true
  validates :description, :presence => true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :authenticate_user!

  def index
    @products = Product.all
    @order_item = current_order.order_items.new
    @order_items = current_order.order_items
  end

  def show
    @product = Product.find(params[:id])
    @order_item = current_order.order_items.new
    @products = Product.all
    respond_to do |format|
      format.html
      format.js
    end
  end

end

app/views/products/_show.html.erb
<h1><%= @product.name %></h1>
<p><%=number_to_currency @product.price %></p>
<p><%= @product.description %></p>

<%= form_for @order_item do |f| %>
  <%= f.hidden_field :product_id, value: @product.id %>
  <p>qty: <%= f.number_field :quantity %></p>
  <p><%= f.submit "Add to cart" %></p>
<% end %>

<% if @product.reviews.any? %>
  <h4>Here are the reviews for this product:</h4>

  <ul>
    <% @product.reviews.each do |review| %>
      <li>
        <p>Review: <%= review.content %></p>
        <p>Author: <%= review.author %></p>
        <p>Rating: <%= review.rating %></p>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no reviews yet!</p>
<% end %>

<% if is_logged_in? %>
  <p><%= link_to "Add a review", new_product_review_path(@product), id: "new_review", remote: true %></p>
<% else %>
  <p><%= link_to 'Log in to add a review!', new_user_session_path %></p>
<% end %>

<p><%= link_to "Return to products", products_path %></p>

app/views/products/index.html.erb
<h1>All Products:</h1>
<br>
<h2>Your cart</h2>
<% if @order_items.any? %>
  <% @order_items.each do |item| %>
    <p><%= item.product.name %> | <%= link_to "Delete", order_item_path(item), :data => {:confirm => "You sure?", :method => "delete"} %></p>
    <p> Unit Price: <%= number_to_currency item.product.price %> | Quantity: <%= item.quantity %> | Total Price: <%= number_to_currency (item.product.price * item.quantity) %></p>
    <br>
  <% end %>
  <hr>
  <p>Your Total: <%= number_to_currency current_order.total_price %></p>
<% else %>
  <p>Your shopping cart is empty.</p>
<% end %>
<div class="row">
  <div class="col-xs-9">
    <div id="product_detail"></div>
  </div>
  <div class="col-xs-3">
    <% @products.each do |product| %>
        <%= link_to product.name, product_path(product), remote: true %> |
          <%= number_to_currency product.price %>
          <%= form_for @order_item do |f| %>
          <%= f.hidden_field :product_id, value: product.id %>
          <p>qty: <%= f.number_field :quantity %></p>
          <p><%= f.submit "Add to cart" %></p>
        <% end %>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<h1>Products Show</h1>

<h1><%= @product.name %></h1>
<p><%=@product.price %></p>
<p><%= @product.description %></p>

<%= form_for @order_item do |f| %>
  <%= f.hidden_field :product_id, value: @product.id %>
  <p>qty: <%= f.number_field :quantity %></p>
  <p><%= f.submit "Add to cart" %></p>
<% end %>

<% if @product.reviews.any? %>
  <h4>Here are the reviews for this product:</h4>

  <ul>
    <% @product.reviews.each do |review| %>
      <li>
        <p>Review: <%= review.content %></p>
        <p>Author: <%= review.author %></p>
        <p>Rating: <%= review.rating %></p>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no reviews yet!</p>
<% end %>

<% if is_logged_in? %>
  <p><%= link_to "Add a review", new_product_review_path(@product), id: "new_review", remote: true %></p>
<% else %>
  <p><%= link_to 'Log in to add a review!', new_user_session_path %></p>
<% end %>

<p><%= link_to "Return to products", products_path %></p>

app/views/products/show.js.erb
$("#product_detail").html("<%= j render ('show')%>");