config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
          sessions: 'users/sessions'
        }

  resources :products do
    resources :reviews
  end

  resources :users do
    resources :accounts
  end

  resources :products
  resources :order_items
  resource :cart, only: [:show]

  root to: "home#index"
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_nav.html.erb
<div id="nav">
  <%=  %>
  <%= link_to 'home', root_path%>
  <%= link_to 'products', products_path %>

  <% if is_logged_in? %>
    <%= link_to 'sign out', destroy_user_session_path, method: 'delete' %>
  <% end %>

  <% if is_admin? %>
    <%= link_to 'admin', rails_admin_path %>
  <% end %>

  <%= current_user.email if current_user %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blackshirts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>